[package]
name = "rustic_messenger"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
dotenv = "0.15.0"
env_logger = "0.11.3"
futures-lite = "2.3.0"
lapin = "2.3.3"
log = "0.4.21"
serde = "1.0.198"
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.12"
